# Generated by Django 4.2.9 on 2024-01-17 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, max_length=150)),
                ('link_type', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('link_id', models.IntegerField(default=0)),
                ('create_date', models.CharField(blank=True, default=datetime.date(2024, 1, 17), max_length=100)),
                ('create_time', models.CharField(blank=True, default='17:52:49', max_length=100)),
                ('update_date', models.CharField(blank=True, default=datetime.date(2024, 1, 17), max_length=100)),
                ('update_time', models.CharField(blank=True, default='17:52:49', max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PyamentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('received_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('due_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
