# Generated by Django 4.2.9 on 2024-01-18 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyamentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('received_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('due_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, max_length=150)),
                ('link_type', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('create_date', models.CharField(blank=True, default=datetime.date(2024, 1, 18), max_length=100)),
                ('create_time', models.CharField(blank=True, default='12:18:44', max_length=100)),
                ('update_date', models.CharField(blank=True, default=datetime.date(2024, 1, 18), max_length=100)),
                ('update_time', models.CharField(blank=True, default='12:18:44', max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.pyamentshistory')),
            ],
        ),
    ]
