# Generated by Django 4.2.9 on 2024-01-19 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='create_date',
            field=models.CharField(blank=True, default=datetime.date(2024, 1, 19), max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='create_time',
            field=models.CharField(blank=True, default='10:04:54', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='update_date',
            field=models.CharField(blank=True, default=datetime.date(2024, 1, 19), max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='update_time',
            field=models.CharField(blank=True, default='10:04:54', max_length=100),
        ),
    ]
