# Generated by Django 3.2.23 on 2024-01-23 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_alter_attachment_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='create_date',
            field=models.CharField(blank=True, default=datetime.date(2024, 1, 23), max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='create_time',
            field=models.CharField(blank=True, default='14:47:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='update_date',
            field=models.CharField(blank=True, default=datetime.date(2024, 1, 23), max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='update_time',
            field=models.CharField(blank=True, default='14:47:00', max_length=100),
        ),
    ]
