# Generated by Django 3.2.23 on 2024-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_auto_20240123_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='create_time',
            field=models.CharField(blank=True, default='14:50:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='update_time',
            field=models.CharField(blank=True, default='14:50:33', max_length=100),
        ),
    ]
