# Generated by Django 5.0.1 on 2024-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('select_application', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('active_users', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
