# Generated by Django 4.2.9 on 2024-01-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.application'),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
        ),
    ]
