# Generated by Django 4.2.9 on 2024-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_remove_customer_select_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
