# Generated by Django 4.2.9 on 2024-01-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_alter_customer_end_date_alter_customer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='url',
        ),
    ]
