# Generated by Django 4.2.9 on 2024-01-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
        ('Industries', '0001_initial'),
        ('Customers', '0007_remove_customer_active_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.application'),
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Industries.industries'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
        ),
    ]
