# Generated by Django 4.2.9 on 2024-01-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0001_initial'),
        ('Applications', '0001_initial'),
        ('Customers', '0008_alter_applicationdetails_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Applications.application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Industries.industries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
        ),
    ]
