# Generated by Django 4.2.9 on 2024-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
        ('Customers', '0009_alter_applicationdetails_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='application',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='application',
            field=models.ManyToManyField(to='Applications.application'),
        ),
    ]
