# Generated by Django 4.2.9 on 2024-01-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
        ('Customers', '0010_remove_applicationdetails_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='application',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Applications.application'),
            preserve_default=False,
        ),
    ]
